apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-monitor
spec:
  selector:
    matchLabels:
      app: simple-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-monitor
    spec:
      containers:
        - name: proxycontainer
          image: lachlanevenson/k8s-kubectl
          command: ["kubectl","proxy","--port=8088"]
          resources:
            requests:
              memory: "512Mi"
              cpu: 250m
            limits:
              memory: "512Mi"
              cpu: 250m
